# Prompt the user for the number of nodes to create
puts "How many nodes do you want to create?"
NUMBER_OF_NODES = STDIN.gets.chomp.to_i

# 
unless NUMBER_OF_NODES > 0
    abort("Invalid number of nodes. Please enter a positive integer.")
end

Vagrant.configure("2") do |config|
    (1..NUMBER_OF_NODES).each do |i|
        config.vm.define "node#{i}" do |node|
            node.vm.hostname = "node#{i}"
            node.vm.box = "hashicorp/bionic64"
            node.vm.network "private_network", ip: "192.168.56.10#{i}"
            node.vm.box_check_update = false
            # Available options for vs (virtualization software) are:
            # a) virtualbox
            # b) vmware_fusion
            # c) hyperv
            node.vm.provider "virtualbox" do |vs|
                vs.name = "node#{i}"
                vs.memory = "1024"
                vs.cpus = "2"
            end
        end
    end
    # Uncomment the following lines, in case of using Ansible and replace 
    # the playbook path with <playbook-path-placeholder>.
    # config.vm.provision "ansible" do |ansible|
    #     ansible.playbook = "<playbook-path-placeholder>"
    # end
end
