# The following dictionary is just a sample for creating cluster. 
# Make sure it has valid values before executing `vagrant up` command.
cluster = {
  "master-1" => { :ip => "192.168.56.101", :cpus => 1, :mem => 1024 },
  "master-2" => { :ip => "192.168.56.102", :cpus => 2, :mem => 1024 },
  "worker-1" => { :ip => "192.168.56.103", :cpus => 1, :mem => 512 }
}
 
Vagrant.configure("2") do |config|
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      # Available options for vs (virtualization software) are:
      # a) virtualbox
      # b) vmware_fusion
      # c) hyperv
      cfg.vm.provider "virtualbox" do |vs, override|
        config.vm.box = "ubuntu/bionic64"
        config.vm.box_check_update = false
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vs.name = hostname
        vs.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
      end
    end
  end
end
