Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_check_update = false
  # Available options for vs (virtualization software) are:
  # a) virtualbox
  # b) vmware_fusion
  # c) hyperv
  config.vm.provider "virtualbox" do |vs|
    vs.memory = "1024"
  end
end
